#!/usr/bin/env python3

from gradelib import *

r = Runner(save("xv6.out"))

@test(1, "forktest")
def test_forktest():
    r.run_qemu(shell_script([
        'forktest'
    ]), timeout=300)
    r.match('^fork test OK$')


run_tests()
